owner: mario-galindo
repo: monitor

sites:
  - name: FPM[Dev] | Authentication API
    url: https://devauth.airlinemro.parts
    __dangerous__disable_verify_peer: true
  
  - name: FPM[Dev] | Management API
    url: https://devmanagement.airlinemro.parts
    __dangerous__disable_verify_peer: true

  - name: FPM[Dev] | Manual Queue API
    url: https://devmqueue.airlinemro.parts
    __dangerous__disable_verify_peer: true

  - name: FPM[Dev] | Frontend
    url: https://devfpm.airlinemro.parts
    __dangerous__disable_verify_peer: true
  
    
assignees:
  - mario-galindo
 

status-website:
  baseUrl: /monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**FPM Status Monitor**"
  introMessage: Status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
